# Site settings
title: VLSI-SoC 2021
description: VLSI-SoC 2021 | 29th IFIP/IEEE International Conference on Very Large Scale Integration > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Valentino Peluso
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build.sh
  - README.md
  - links.md
